### ISSUE TITLE
Can't save Masquerade fields after edit

### ISSUE THREAD

**Issue by miniluigi008** [flagrow/masquerade#6] opened 2017-06-19 23:00 UTC
When I try to click on the "Edit field" button after making some changes to a field, an error pops up at the bottom saying 'Oops! Something went wrong. Please reload the page and try again.'

I would provide an error log but I'm not sure where to find it for this specific extension.
I'm using version 0.1.0-beta.6 of Flarum, PHP 5.6.25, and 0.1.0 of Masquerade.

Any help is appreciated.

**Comment by Luceos** [comment] 2017-06-20 04:58
Can you enable debug and see what the debug buttons on the woops modal gives as information? Otherwise the logs can be found in `storage/logs/flarum.log`.

**Comment by miniluigi008** [comment] 2017-06-20 15:24
Yeah, I didn't see anything recent in the flarum.log so I'll enable debug...

Okay, upon further inspection it seems this is the problem:

`"errors": [
    {
      "code": 500,
      "title": "Internal server error",
      "detail": "exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'excerpt_length' in 'field list'' in [omitted]/vendor/illuminate/database/Connection.php:411`

The rest of the error is just a stack trace (there aren't any other errors.)

**Comment by miniluigi008** [comment] 2017-06-20 15:31
Okay, upon even further inspection, the delete field button does not work either. It gives no error, though. Strangely, the trash bin button at the top does work, which is the button I have been using to delete the fields.

**Comment by Luceos** [comment] 2017-06-20 19:42
excerpt length is not part of this extension.. Can you run `php flarum migrate` or disable all other extensions temporarily?

**Comment by miniluigi008** [comment] 2017-06-20 23:13
Running `php flarum migrate` gives me an error `PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in [omitted]/vendor/illuminate/database/Connectors/Connector.php:55`. I'll try disabling all my other extensions.

**Comment by miniluigi008** [comment] 2017-06-20 23:21
Okay, I disabled all other extensions except for my other Flagrow extensions and the ones that come with Flarum by default. No error is shown after clicking Edit Field now, but the delete field button does still not work, yet the trash bin does. I'm going to re-enable the extensions one by one in debug mode to see which one is conflicting.

**Comment by miniluigi008** [comment] 2017-06-20 23:26
Okay, I figured out which extension is causing the problem.

It appears to be `https://github.com/jordanjay29/flarum-ext-summaries` which is causing the issue.

**Comment by miniluigi008** [comment] 2017-06-20 23:37
Alright, I enabled all other extensions except ext-summaries and your plugin works perfectly.
Since summaries doesn't really conflict with masquerade anywhere else, I suppose a temporary workaround would be to disable summaries whenever I need to edit the profile page template.

I would drop an issue on the summaries repo but I would think that it is best left to the extension maintainers to figure out where the extensions conflict, yeah? I wouldn't really be of any help at this point.

Thank you for your time and your wonderful plugin!

**Comment by Luceos** [comment] 2017-06-21 04:32
Now that you fixed that socket, try running migrate again.

/ping @jordanjay29 for his summaries extension, perhaps he can give you additional suggestions on this problem.

**Comment by miniluigi008** [comment] 2017-06-21 19:28
I ran `php flarum migrate` which worked successfully this time due to the fixed socket, but the same missing column error persists when both summaries and masquerade are enabled.

@jordanjay29 Any ideas?

**Comment by Luceos** [comment] 2017-06-22 06:40
Hi @miniluigi008 I've already had a chat with Jordan, we both found nothing that might point to the cause of this issue. Can you post the full error "trace" from `storage/log/flarum.log`?

**Comment by miniluigi008** [comment] 2017-06-22 12:26
Here is the flarum log, there seem to be only two traces related to this issue in it, even though I experienced it more than twice.
[flarum log.txt](https://github.com/flagrow/masquerade/files/1094715/flarum.log.txt)

Here is the full error trace from the "Oops!" Debug selection on the web.
[Debug Error.txt](https://github.com/flagrow/masquerade/files/1094716/Debug.Error.txt)

**Comment by Luceos** [comment] 2017-06-22 12:30
For your information the interesting part is this:

```
#9 /[omitted webroot]/forums/vendor/flagrow/masquerade/src/Repositories/FieldRepository.php(66): Illuminate\\Database\\Eloquent\\Model->save()\n
#10 /[omitted webroot]/forums/vendor/flagrow/masquerade/src/Api/Controllers/SaveFieldController.php(55): Flagrow\\Masquerade\\Repositories\\FieldRepository->findOrNew(Array)
```

I'll look into it. I might have an idea where this comes from.

**Comment by Luceos** [comment] 2017-06-22 12:33
@miniluigi008 one last thing, can you post your `require` section of the `composer.json` ;)

**Comment by miniluigi008** [comment] 2017-06-22 12:42
```
    "require": {
        "flarum/core": "^0.1.0",
        *"flarum/flarum-ext-akismet": "^0.1.0",
        "flarum/flarum-ext-approval": "^0.1.0",
        *"flarum/flarum-ext-auth-facebook": "^0.1.0",
        *"flarum/flarum-ext-auth-github": "^0.1.0",
        *"flarum/flarum-ext-auth-twitter": "^0.1.0",
        "flarum/flarum-ext-bbcode": "^0.1.0",
        "flarum/flarum-ext-emoji": "^0.1.0",
        "flarum/flarum-ext-english": "^0.1.0",
        "flarum/flarum-ext-flags": "^0.1.0",
        *"flarum/flarum-ext-likes": "^0.1.0",
        "flarum/flarum-ext-lock": "^0.1.0",
        "flarum/flarum-ext-markdown": "^0.1.0",
        "flarum/flarum-ext-mentions": "^0.1.0",
        *"flarum/flarum-ext-pusher": "^0.1.0",
        "flarum/flarum-ext-sticky": "^0.1.0",
        "flarum/flarum-ext-subscriptions": "^0.1.0",
        "flarum/flarum-ext-suspend": "^0.1.0",
        "flarum/flarum-ext-tags": "^0.1.0",
        "zendframework/zend-stratigility": "1.2.*",
        "datitisev/flarum-ext-dashboard": "^0.1.0@beta",
        "flagrow/flarum-ext-latex": "^0.1.1",
        "sijad/flarum-ext-links": "^0.1.0@beta",
        "avatar4eg/flarum-ext-users-list": "^0.1.1",
        "s9e/flarum-ext-mediaembed": "^0.3.2",
        *"davis/flarum-ext-securehttps": "^0.1.0@beta",
        "davis/flarum-ext-inviteonly": "^0.1.0@beta",
        "flagrow/byobu": "^0.1.0@beta",
        *"antoinefr/flarum-ext-money": "^0.3.0",
        "flagrow/upload": "0.5.7",
        "sijad/flarum-ext-details": "^0.1.2",
        "jordanjay29/flarum-ext-summaries": "^0.2.0",
        "flagrow/masquerade": "^0.1.0",
        "wiwatsrt/flarum-ext-best-answer": "^0.1.0@beta",
        "davis/flarum-ext-split": "^0.1.0@beta",
        "clarkwinkelmann/flarum-ext-circle-groups": "^0.1.0@beta",
        "oe800/flarum-ext-bbcode-special": "^0.1.4",
        "reflar/gamification": "^1.0@RC",
        *"oe800/flarum-gravatar": "^0.1.2",
        "oe800/flarum-ext-bbcode-cards": "^0.1.4",
        "oe800/flarum-ext-bbcode-alerts": "^0.1.5",
        "oe800/flarum-ext-bbcode-bars": "^0.1.5",
        "johnhearfield/flarum-ext-landing-page": "^0.1.0@beta",
        "clarkwinkelmann/flarum-ext-emojionearea": "^0.1.1"
    }
```

I've put an asterisk by the ones that are currently disabled. As you can see, I'm a big fan of flagrow extensions. 😏

**Comment by Luceos** [comment] 2017-06-22 12:52
Great thanks! Cool to see that abandoned latex extension still works 😊

**Comment by Luceos** [comment] 2017-06-22 12:59
So the only extension of all of these is summaries that uses excerpt_length:

![image](https://user-images.githubusercontent.com/504687/27435110-53bbfb18-575b-11e7-91c1-a5281e095cfd.png)

**Comment by luceos** [comment] 2017-07-10 09:22
I still think this is unrelated to this extension and so will close this issue here.

**Comment by luceos** [comment] 2017-07-19 11:30
Okay found the issue!

**Closed** 2017-07-19 11:50 UTC

**Comment by miniluigi008** [comment] 2017-07-24 03:35
Thank you! @jordanjay29 @luceos
